// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqnSkEr6e4RSoiKPnFvndXJc10O_W77MM',
    appId: '1:959185985485:web:638ee755b6fbb26b6eee84',
    messagingSenderId: '959185985485',
    projectId: 'cowboydodartinc-r162vk',
    authDomain: 'cowboydodartinc-r162vk.firebaseapp.com',
    databaseURL: 'https://cowboydodartinc-r162vk-default-rtdb.firebaseio.com',
    storageBucket: 'cowboydodartinc-r162vk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNNiC9SVslqZyFbqyUdYMLJ1yrDMWyY24',
    appId: '1:959185985485:android:d1b118f752d0cbd86eee84',
    messagingSenderId: '959185985485',
    projectId: 'cowboydodartinc-r162vk',
    databaseURL: 'https://cowboydodartinc-r162vk-default-rtdb.firebaseio.com',
    storageBucket: 'cowboydodartinc-r162vk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLadwKyVlQ6b8npVvYsRVDC0LqP5q_w5E',
    appId: '1:959185985485:ios:e37f977a0e1e1ab86eee84',
    messagingSenderId: '959185985485',
    projectId: 'cowboydodartinc-r162vk',
    databaseURL: 'https://cowboydodartinc-r162vk-default-rtdb.firebaseio.com',
    storageBucket: 'cowboydodartinc-r162vk.firebasestorage.app',
    androidClientId: '959185985485-hjubmstk6rpdvdif2i7orosffnfq5v6c.apps.googleusercontent.com',
    iosClientId: '959185985485-pune2u670af1fo299aaqk80h7ei8rsj1.apps.googleusercontent.com',
    iosBundleId: 'com.cowboydodartinc.app',
  );
}
