// Google Sign-In Client IDs for Supabase backend.
//
// ⚠️  Auto-generated by the CLI from the credentials you provided.
// Re-run `kasy new` or edit manually to update.
//
// Web Client ID: console.cloud.google.com → Credentials → OAuth 2.0 → Web application
// iOS Client ID: console.cloud.google.com → Credentials → OAuth 2.0 → iOS

/// Web / Server Client ID — used as serverClientId on Android and for
/// the Supabase provider configuration.
const kGoogleWebClientId = '959185985485-amppl9k8v8jlrcuo36kup3q7akkht118.apps.googleusercontent.com';

/// iOS OAuth 2.0 Client ID — required for native Sign-In on iOS.
const kGoogleIosClientId = '959185985485-pune2u670af1fo299aaqk80h7ei8rsj1.apps.googleusercontent.com';
